name: Build
on:
  workflow_dispatch:
    inputs:
          full-sha:
            description: 'Git commit full SHA'
            required: true
  push:
    branches: 
      - 'release/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.full-sha && github.event.inputs.full-sha ||  env.GITHUB_SHA  }}
      - name: Variable CURRENT_DATE
        if: github.ref == 'refs/heads/master'
        id: current-date
        run: |
          echo ::set-output name=CURRENT_DATE::$(date +'%Y-%m-%d')
      - name: Create Release Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release/{{steps.current-date.outputs.CURRENT_DATE}}'