name: Build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Slack Notification 3
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,message,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                title: ':rocket: Deploy to Test',
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `Project: ${ process.env.AS_REPO }\nWorkflow: ${ process.env.AS_WORKFLOW }\nPull Request: <https://github.com/katu-digital/${{ github.event.repository.name }}/pull/${{ steps.findPr.outputs.number }}|${{ steps.findPr.outputs.title}}>`
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()