name: Build
on:
  workflow_dispatch:
    inputs:
          full-sha:
            description: 'Git commit full SHA'
            required: true
  push:
    branches: 
      - 'release/**'
jobs:
  release-branch:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.full-sha }}
          token: ${{ secrets.PAT }}
      - name: Variable RELEASE_BRANCH_NAME
        id: release-branch-name
        run: |
          echo ::set-output name=RELEASE_BRANCH_NAME::release/$(date +'%Y-%m-%d')
      - name: Create Release Branch
        run: |
          git checkout -b ${{ steps.release-branch-name.outputs.RELEASE_BRANCH_NAME }}
          git push origin ${{ steps.release-branch-name.outputs.RELEASE_BRANCH_NAME }}
  deploy:
    runs-on: ubuntu-latest
    if: contains(github.ref, "release/")
    outputs:
      GIT_REF: ${{steps.var-git-ref.outputs.GIT_REF}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          echo "Deploy"