name: Build
on:
  workflow_dispatch:
    inputs:
          full-sha:
            description: 'Git commit full SHA'
            required: true
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.full-sha && github.event.inputs.full-sha ||  env.GITHUB_SHA  }}